### ISSUE TITLE
Update examples to include more countries

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-typeahead#39]
The current examples [only define 3 countries](https://github.com/alphagov/accessible-typeahead/blob/master/examples/index.html#L107-L109). Having at least one example with lots of countries would help with testing scrolling behaviours.

**Comment by ganes1410** [comment]
I will do this.How many countries do i need to add?

**Comment by tvararu** [comment]
Hi @ganes1410, feel free to hardcode a list based on something like the [GOV.UK country register](https://country.register.gov.uk/records) 👍

**Comment by GeneralMeow** [comment]
Hey there,
is this still open to work on?

**Comment by tvararu** [comment]
Closed by #45.

**Comment by tvararu** [comment]
@GeneralMeow sorry! This one's been done. Please pick up another issue or come back in a while after more pop up. :)
