### ISSUE TITLE
Plan for 1.0.0

### ISSUE THREAD

**Issue by adammockor** [alphagov/accessible-typeahead#60]
Hello,

This plugin looks really good, so is there a plan for 1.0.0?

What needs to be done to remove this `⚠️ WARNING: This project is still experimental / under development. Do not use in production. ⚠️` warning?

Thank you!

**Comment by tvararu** [comment]
Hi @adammockor, thanks for tuning in, and for noticing the README clause. ;)

The typeahead has already been in 4 rounds of user research, and we have 1 more in the following weeks with users with access needs. It has also been informally tested by some wonderful people at the [Digital Accessibility Centre](http://www.digitalaccessibilitycentre.org/) (we have a blog post coming out soon about this on [the GDS blog](https://gds.blog.gov.uk/)). It will also have to pass a formal assessment from the DAC.

Once those are done, there are a few more productisation issues are ironed out, such as supporting multiple package managers and distribution channels, and automated end to end testing across a wide range of browsers. 

After that, we should be confident enough to release it.

Within the next weeks I should start opening issues and a "path to v1" milestone relating to this.

Until then we advise you not to use it, unless your service is a throwaway prototype and you are willing to experiment.

**Comment by adammockor** [comment]
Thank you for detailed explanation, if you will need any help let me know!

**Comment by tvararu** [comment]
@adammockor please feel free to dive into and submit pull request for any of the issues that you find interesting! The ones marked as "good for beginners" should be approachable to people new to the codebase, and I'll help with any information you need.

**Comment by tvararu** [comment]
I've opened the [v1.0.0 milestone](https://github.com/alphagov/accessible-typeahead/milestone/2) and will begin populating it shortly.
