### ISSUE TITLE
Suggest change to success criterion 8 - number of matches

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/accessible-typeahead#65]
Criterion 8 currently says:
"Inform the user that N number of matches have been displayed"

I wonder if this should be:
"Inform the user when there are matches, or if there are no matches"

With another:
"(Optional) inform the user the number of matches"

I also wonder if criterion 9 should be made optional.

Reasoning: for sighted users, we don't display the number of matches - what we *do* indicate is whether there *are* matches. Is it crucial that a screen reader user is told whether there are 3 or 5 matches? or is the essential thing that they be told when there are results and when there aren't?

**Comment by tvararu** [comment]
I agree that the crucial behaviour is expressing that matches are available. We should reflect that in the criteria with the changes you've outlined. 👍 

> Reasoning: for sighted users, we don't display the number of matches

Nitpick: you can visually count the number of matches, unless scrolling kicks in, so this isn't true for all use cases. It's still mostly true.
