### ISSUE TITLE
Change project name from typeahead to autocomplete

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/accessible-typeahead#66]
We recently decided to refer to this as an autocomplete rather than a typeahead. Autocomplete felt more natural and appears to be in more common usage (comparing similar components and search terms).

To do:
* Change repo name
* Change readme docs
* Change internal references

**Comment by nickcolley** [comment]
Also need to republish the package on npm

**Comment by adamsilver** [comment]
Also don't put "Accessible" in front of it.

**Comment by edwardhorsford** [comment]
@adamsilver what's your reasoning?

**Comment by adamsilver** [comment]
If we're going to put "accessible" in the name then why not put other things in it too:

- "well-designed-autocomplete"
- "really-good-progressively-enhanced-responsive-autocomplete"
- "fast-well-tested-autocomplete"

Accessible is *one* of many qualities of a well designed component. Why emphasis this one aspect?

**Comment by tvararu** [comment]
I think `accessible` is great for marketing (people search for "accessible \<thing\>" all the time). It also makes accessibility non-negotiable, because it's right there in the name.

**Comment by adamsilver** [comment]
Fair enough. Will GDS (re)name all components "accessible-etc"?

**Comment by joelanman** [comment]
it does seem odd, and would mean we'd have to name other components accessible-

**Comment by tvararu** [comment]
@joelanman @adamsilver I disagree we'd have to extend the naming. We don't follow strict guidance on naming projects as far as I'm aware of? Separate discussion about this can be had but until then projects get named all sorts of things. (`govuk-` in projects that aren't used by GOVUK is another weird theme)

Autocompletes are notoriously hard to get right from an accessibility standpoint. I think it's worth leveraging this as a selling point. I also think the alliteration in `accessible-autocomplete` is catchy.

Or we can go for `gds-autocomplete`, or `govuk-autocomplete`, tbh this is a bikeshed discussion. Picking a name is important but being stuck debating isn't useful.

**Comment by edwardhorsford** [comment]
Might be worth a discussion with Alice and Tim.

It being an accessible typeahead is arguably the main selling point. More than that, where there have been design dilemmas, we've erred on the side of accessibility. Some of the features we might have wanted to do we couldn't because of this.

We could go with `govuk-autocomplete` but we're hoping this component may be generically useful outside of government too, so not having `govuk` in the name may be helpful.

**Comment by joelanman** [comment]
govuk would be more consistent with other things we provide (elements, prototype kit, notify, etc) and I don't think it stops usage outside of government. It could be useful for people to be aware of where this good work comes from.
